// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

type Credential struct {
	ID              []byte
	UserID          []byte
	PublicKey       []byte
	AttestationType string
	Transport       []string
	Flags           []byte
	Authenticator   []byte
	Attestation     []byte
}

type User struct {
	ID          []byte
	DisplayName string
	Name        string
}
