// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

type Session struct {
	UserID      []byte
	SessionID   string
	SessionData []byte
}

type User struct {
	ID          []byte
	DisplayName string
	Name        string
	Credentials []byte
}
