// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, display_name, name)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	ID          []byte
	DisplayName string
	Name        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.DisplayName, arg.Name)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, display_name, name FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, display_name, name FROM users
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(&i.ID, &i.DisplayName, &i.Name)
	return i, err
}

const getUserCredsById = `-- name: GetUserCredsById :one
SELECT id, user_id, public_key, attestation_type, transport, flags, authenticator, attestation from credentials
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserCredsById(ctx context.Context, id []byte) (Credential, error) {
	row := q.db.QueryRow(ctx, getUserCredsById, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transport,
		&i.Flags,
		&i.Authenticator,
		&i.Attestation,
	)
	return i, err
}
